Move some path setup to .zshenv
Needed to fix below neovide issue.

	Neovide just crashed :(
	This is the error that caused the crash. In case you don't know what to do with this, please feel free to report this on https://github.com/neovide/neovide/issues!

	ERROR: Unexpected output from neovim binary:
		nvim not found -v
	stdout:
	stderr: zsh:1: command not found: nvim

	Please check your shell configuration.
	$SHELL -lc 'nvim not found -v'